# Generated by Django 2.1.5 on 2019-01-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExAlumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonios',
            fields=[
                ('id_testimonio', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.CharField(max_length=255)),
                ('id_exalumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExAlumnos.Exalumnos')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'testimonios',
                'db_table': 'testimonios',
            },
        ),
    ]
