# Generated by Django 2.1.5 on 2019-02-11 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ExAlumnos', '0002_auto_20190117_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonios',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'testimonios'},
        ),
        migrations.AlterField(
            model_name='testimonios',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
