# Generated by Django 2.1.5 on 2019-02-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Primer Ciclo', 'Primer Ciclo'), ('Segundo Ciclo', 'Segundo Ciclo'), ('Tercer Ciclo', 'Tercer Ciclo'), ('Cuarto Ciclo', 'Cuarto Ciclo'), ('Quinto Ciclo', 'Quinto Ciclo'), ('Sexto Ciclo', 'Sexto Ciclo'), ('Septimo Ciclo', 'Septimo Ciclo'), ('Octavo Ciclo', 'Octavo Ciclo'), ('Noveno Ciclo', 'Noveno Ciclo'), ('Decimo Ciclo', 'Decimo Ciclo')], default='Primer Ciclo', max_length=255)),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'db_table': 'ciclo',
            },
        ),
        migrations.CreateModel(
            name='malla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', '1'), ('Desactivado', '0')], default='Activo', max_length=1)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(auto_now_add=True)),
                ('nro_ciclos', models.CharField(max_length=2)),
                ('malla_activa', models.CharField(choices=[('Actual', '1'), ('Antigua', '0')], default='Actual', max_length=1)),
            ],
            options={
                'verbose_name': 'Malla',
                'verbose_name_plural': 'Mallas',
                'db_table': 'malla',
            },
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('es_cadena', models.CharField(choices=[('Si', '1'), ('No', '0')], default='Si', max_length=1)),
                ('tiene_prerequisitos', models.CharField(choices=[('Si', '1'), ('No', '0')], default='No', max_length=1)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_edicion', models.DateTimeField(auto_now_add=True)),
                ('es_materia_periodo_extraordinario', models.CharField(choices=[('Si', '1'), ('No', '0')], default='No', max_length=1)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='materia_malla_ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academia.malla')),
                ('id_malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academia.malla')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academia.materia')),
            ],
            options={
                'verbose_name': 'materia_malla_ciclo',
                'verbose_name_plural': 'materias_mallas_ciclos',
                'db_table': 'materia_malla_ciclo',
            },
        ),
        migrations.CreateModel(
            name='materia_prerequisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.materia')),
                ('id_materia_malla_ciclo_antecesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.materia_malla_ciclo')),
            ],
            options={
                'verbose_name': 'materia_prerequisito',
                'verbose_name_plural': 'materias_prerequisitos',
                'db_table': 'materia_prerequisito',
            },
        ),
    ]
