# Generated by Django 2.1.5 on 2019-02-13 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('1ro', 'Primer Ciclo'), ('2do', 'Segundo Ciclo'), ('3ro', 'Tercer Ciclo'), ('4to', 'Cuarto Ciclo'), ('5to', 'Quinto Ciclo'), ('6to', 'Sexto Ciclo'), ('7mo', 'Septimo Ciclo'), ('8vo', 'Octavo Ciclo'), ('9no', 'Noveno Ciclo'), ('10mo', 'Decimo Ciclo')], default='1ro', max_length=255)),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'db_table': 'ciclo',
            },
        ),
        migrations.CreateModel(
            name='malla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(auto_now_add=True)),
                ('nro_ciclos', models.CharField(max_length=2)),
                ('isMallaActiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Malla',
                'verbose_name_plural': 'Mallas',
                'db_table': 'malla',
            },
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('esCadena', models.BooleanField(default=True)),
                ('tiene_prerequisitos', models.BooleanField(default=False)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_edicion', models.DateTimeField(auto_now_add=True)),
                ('es_materia_periodo_extraordinario', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='materia_malla_ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iden_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mciclo', to='academia.malla')),
                ('iden_malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.malla')),
                ('iden_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.materia')),
            ],
            options={
                'verbose_name': 'materia_malla_ciclo',
                'verbose_name_plural': 'materias_mallas_ciclos',
                'db_table': 'materia_malla_ciclo',
            },
        ),
        migrations.CreateModel(
            name='materia_prerequisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.materia')),
                ('materia_malla_ciclo_antecesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.materia_malla_ciclo')),
            ],
            options={
                'verbose_name': 'materia_prerequisito',
                'verbose_name_plural': 'materias_prerequisitos',
                'db_table': 'materia_prerequisito',
            },
        ),
    ]
