# Generated by Django 2.1.5 on 2019-02-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fecha_academica_importante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_importante', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'fecha_academica_importante',
                'verbose_name_plural': 'fechas_academicas_importantes',
                'db_table': 'fecha_academica_importante',
            },
        ),
    ]
