# Generated by Django 2.1.5 on 2019-03-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_fecha_academica_importante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha_academica_importante',
            name='fecha_importante',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='malla',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='malla',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
